"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isTypedArray = exports.isRecord = exports.unixTimeToUnixTimeMillis = exports.unixTimeToDate = exports.unixTimeMillisToUnixTime = exports.unixTimeMillisToDate = exports.isUnixTimeMillis = exports.isUnixTime = exports.dateToUnixTimeMillis = exports.dateToUnixTime = void 0;
const Date_1 = require("./Date");
Object.defineProperty(exports, "dateToUnixTime", { enumerable: true, get: function () { return Date_1.dateToUnixTime; } });
Object.defineProperty(exports, "dateToUnixTimeMillis", { enumerable: true, get: function () { return Date_1.dateToUnixTimeMillis; } });
Object.defineProperty(exports, "isUnixTime", { enumerable: true, get: function () { return Date_1.isUnixTime; } });
Object.defineProperty(exports, "isUnixTimeMillis", { enumerable: true, get: function () { return Date_1.isUnixTimeMillis; } });
Object.defineProperty(exports, "unixTimeMillisToDate", { enumerable: true, get: function () { return Date_1.unixTimeMillisToDate; } });
Object.defineProperty(exports, "unixTimeMillisToUnixTime", { enumerable: true, get: function () { return Date_1.unixTimeMillisToUnixTime; } });
Object.defineProperty(exports, "unixTimeToDate", { enumerable: true, get: function () { return Date_1.unixTimeToDate; } });
Object.defineProperty(exports, "unixTimeToUnixTimeMillis", { enumerable: true, get: function () { return Date_1.unixTimeToUnixTimeMillis; } });
const utilsForTypeGuard_1 = require("./utilsForTypeGuard");
Object.defineProperty(exports, "isRecord", { enumerable: true, get: function () { return utilsForTypeGuard_1.isRecord; } });
Object.defineProperty(exports, "isTypedArray", { enumerable: true, get: function () { return utilsForTypeGuard_1.isTypedArray; } });
